name: Java CI

on:
  pull_request:
  push:
    branches:
      - publish

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build
      run: ./gradlew build -i
    - name: Push to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker buildx create --name mybuilder --use
        docker buildx build --push --platform linux/amd64,linux/arm64 -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/hmcts/rse/rse-idam-simulator:latest .
#      if: github.ref == 'refs/heads/master'



